/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package introsqlite;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.HBox;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) {

        ListPane listPane = new ListPane();
        FormPane formPane = new FormPane(listPane);

        HBox hBox = new HBox(formPane.getFormPane(), listPane.getListPane());
        hBox.setStyle("-fx-background-color: #0000ff");

        Scene scene = new Scene(hBox, 800, 600);
        primaryStage.setScene(scene);
        primaryStage.setResizable(false);
        primaryStage.show();

    }

    public static void main(String[] args) {
        launch(args);
    }
}
